---

- hosts: condor
  become: yes
  become_method: sudo
  vars_files:
  - {{ path_to_plays }}/cyvars.yaml

  tasks:
  - name: update condor for ubuntu nodes
    apt: name=condor state=latest update_cache=yes
    notify:
      - restart condor
    when: not ansible_check_mode and ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
  - name: update condor on centos
    yum: name={{ condor_version }} state=present update_cache=yes
    notify: 
      - restart condor
    when: not ansible_check_mode and ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - name: ensure condor is running
    service: name=condor state=started
  handlers:
    - include: {{ path_to_plays }}/roles/htcondor/handlers/main.yaml

