- name: change condor config for workers
  lineinfile:
    backup: yes
    path: /etc/condor/condor_config
    create: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^ALLOW_READ ', line: 'ALLOW_READ            = *' }
    - { regexp: '^ALLOW_WRITE ', line: 'ALLOW_WRITE           = *' }
    - { regexp: '^ALLOW_ADMINISTRATOR ', line: 'ALLOW_ADMINISTRATOR   = *' }
    - { regexp: '^ALLOW_CONFIG ', line: 'ALLOW_CONFIG          = *' }
    - { regexp: '^ALLOW_NEGOTIATOR ', line: 'ALLOW_NEGOTIATOR      = *' }
    - { regexp: '^ALLOW_DAEMON ', line: 'ALLOW_DAEMON          = *' }
    - { regexp: '^HOSTALLOW_READ =', line: 'HOSTALLOW_READ =' }
    - { regexp: '^HOSTALLOW_WRITE =', line: 'HOSTALLOW_WRITE =' }
    - { regexp: '^HOSTALLOW_DAEMON =', line: 'HOSTALLOW_DAEMON =' }
    - { regexp: '^HOSTALLOW_NEGOTIATOR =', line: 'HOSTALLOW_NEGOTIATOR =' }
    - { regexp: '^HOSTALLOW_ADMINISTRATOR =', line: 'HOSTALLOW_ADMINISTRATOR =' }
    - { regexp: '^HOSTALLOW_OWNER =', line: 'HOSTALLOW_OWNER ='}
    - { regexp: '^BIND_ALL_INTERFACES =', line: 'BIND_ALL_INTERFACES = True' }
    - { regexp: '^NETWORK_INTERFACE =', line: '#NETWORK_INTERFACE = eth0' }
    - { regexp: '^CONDOR_HOST =', line: "CONDOR_HOST = {{ manager_ip }}" }
    - { regexp: '^COLLECTOR_HOST =', line: 'COLLECTOR_HOST = $(CONDOR_HOST):4080?sock=collector' }
    #- { regexp: '^SCHEDD_HOST =', line: 'SCHEDD_HOST = submit' }
    - { regexp: '^SLOT_TYPE_1 =', line: 'SLOT_TYPE_1 = cpus=100%,disk=100%,swap=100%' }
    - { regexp: '^SLOT_TYPE_1_PARTITIONABLE =', line: 'SLOT_TYPE_1_PARTITIONABLE = True' }
    - { regexp: '^NUM_SLOTS_TYPE_1 =', line: 'NUM_SLOTS_TYPE_1 = 1' }
    - { regexp: '^DAEMON_LIST =', line: 'DAEMON_LIST = MASTER, STARTD' }
    - { regexp: '^LOWPORT =', line: 'LOWPORT = 5000' }
    - { regexp: '^HIGHPORT =', line: 'HIGHPORT = 6000' }
    - { regexp: '^DOCKER =', line: 'DOCKER = /usr/bin/docker' }
    - { regexp: '^ENABLE_IPV6 =', line: 'ENABLE_IPV6 = false' }
  notify:
    - restart condor
- name: add condor to docker group
  user: groups=docker name=condor state=present append=yes
  notify:
    - restart condor
