- name: install ntp
  yum: name=ntp state=present

- name: change configuration
  copy:
    src: /etc/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: u+rw,g-wx,o-wx
  notify:
    - restart ntpd

- name: start ntp at boot
  service: name=ntpd enabled=yes
  become: yes
  become_method: sudo
