- name: uninstall old docker versions
  yum: name={{ item }} state=absent
  with_items:
  - docker
  - docker-common
  #- docker-selinux this seems to exists in the new versions and keep deleting all docker! not ok
  - docker-engine
- name: installing required packages
  yum: name={{ item }} state=present
  with_items:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
- name: setup stable repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644
- name: install docker
  yum: name=docker-ce-17.06.0.ce-1.el7.centos state=present update_cache=yes
  when: not ansible_check_mode #this is needed as in check mode the repo is not there
  notify:
  - restart docker
